pipeline:
  build:
    image: docker
    commands: 
      - docker build -t sravan1265/Drone-AWS .
#      - docker tag sravan1265/Drone-AWS 
      - docker push sravan1265/Drone-AWS:vcx-1.0
  
        
