pipeline:
  build:
    image: plugins/docker
#    commands:
#      - docker build -t aws .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    repo: sravank/vcloudx
    username: sravank	
    password: asdfghjkl
    repo: sravank/vcloudx
    auto_tag: true 
