pipeline:
  build:
    image: docker
    commands:
      - docker build -t thursday .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tag: ${DRONE_TAG}
#    event:
#      when: push
