pipeline:
  build:
    image: docker
    commands:
      - docker build -t sravan1265/Drone-AWS .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
