pipeline:
  build:
    image: docker
    commands: 
      - docker build -t sravank/vcloudx .
#      - docker tag sravan1265/Drone-AWS 
      - docker push sravank/vcloudx:vcx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
        
